# Generated by Django 4.1.7 on 2023-10-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfimapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='nota',
            field=models.FloatField(null=True),
        ),
    ]
