# Generated by Django 4.1.7 on 2023-12-16 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfimapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfimapp.sede'),
        ),
    ]
